Vagrant.configure(2) do |config|

	# before you must install these plugins to speed up vagrant provisionning
  # vagrant plugin install vagrant-faster
  # vagrant plugin install vagrant-cachier

  config.cache.auto_detect = true
	# Set some variables
  etcHosts = ""
  kafka = ""
  kraft = ""
  kafkaManager = ""
  prometheus = ""

  # Check ingress controller
  case ARGV[0]
    when "provision", "up"

    print "Do you want to install kafka (yes/no) ?\n"
    kafka = STDIN.gets.chomp
    print "\n"

    if kafka == "yes"

      print "Do you want to install kafka manager (yes/no) ?"
      kafkaManager = STDIN.gets.chomp

     	print "Do you want to install kafka with kraft (yes/no)  ?"
     	kraft = STDIN.gets.chomp

     	print "Do you want to install one more zookeeper (yes/no)  ?"
     	add_zookeeper = STDIN.gets.chomp

    end


  end

	# some settings for common server (not for haproxy)
  common = <<-SHELL
  sudo apt update -qq 2>&1 >/dev/null
  sudo apt install -y -qq curl openjdk-11-jre-headless software-properties-common git vim tree net-tools telnet git resolvconf 2>&1 >/dev/null
  sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
  sudo systemctl restart sshd
  SHELL

  #config.vm.box = "debian/bullseye64"
  #config.vm.box_url = "debian/bullseye64"
	config.vm.box = "ubuntu/focal64"
	config.vm.box_url = "ubuntu/focal64"


	# set servers list and their parameters
	NODES = [
  	{ :hostname => "kafka1", :ip => "192.168.12.78", :cpus => 2, :mem => 2048, :type => "kafka" },
  	{ :hostname => "kafka2", :ip => "192.168.12.79", :cpus => 2, :mem => 2048, :type => "kafka" },
  	{ :hostname => "kafka3", :ip => "192.168.12.80", :cpus => 2, :mem => 2048, :type => "kafka" },
  	{ :hostname => "zook1", :ip => "192.168.12.82", :cpus => 2, :mem => 2048, :type => "zookeeper" },
  	{ :hostname => "zook2", :ip => "192.168.12.83", :cpus => 2, :mem => 2048, :type => "zookeeper" },
  	{ :hostname => "zook3", :ip => "192.168.12.84", :cpus => 2, :mem => 2048, :type => "zookeeper" },
  	{ :hostname => "kmanager", :ip => "192.168.12.77", :cpus => 2, :mem => 1024, :type => "external" }
	]
	# define /etc/hosts for all servers
  NODES.each do |node|
			etcHosts += "echo '" + node[:ip] + "   " + node[:hostname] + "'>> /etc/hosts" + "\n"
  end #end NODES

	# run installation
  NODES.each do |node|
    config.vm.define node[:hostname] do |cfg|
			cfg.vm.hostname = node[:hostname]
      cfg.vm.network "private_network", ip: node[:ip]
      cfg.vm.provider "virtualbox" do |v|
				v.customize [ "modifyvm", :id, "--cpus", node[:cpus] ]
        v.customize [ "modifyvm", :id, "--memory", node[:mem] ]
        v.customize [ "modifyvm", :id, "--natdnshostresolver1", "on" ]
        v.customize [ "modifyvm", :id, "--natdnsproxy1", "on" ]
        v.customize [ "modifyvm", :id, "--name", node[:hostname] ]
				v.customize [ "modifyvm", :id, "--ioapic", "on" ]
        v.customize [ "modifyvm", :id, "--nictype1", "virtio" ]
      end #end provider
			
			#for all
			cfg.vm.provision :shell, :path => "../_generic_scripts/install_xavki.sh"
      cfg.vm.provision :shell, :inline => etcHosts
			cfg.vm.provision :shell, :inline => common
      cfg.vm.provision :shell, :path => "install_resolvdns.sh"

      if kafka == "yes"
        if node[:type] == "kafka"
          cfg.vm.provision :shell, :path => "install_kafka.sh", :args => kraft
			  end
			end
      if kafka == "yes"
        if node[:type] == "zookeeper" && add_zookeeper == "yes"
          cfg.vm.provision :shell, :path => "install_zookeeper.sh"
			  end
			end
      if kafkaManager == "yes"
        if node[:type] == "external"
          cfg.vm.provision :shell, :path => "install_bind.sh"
          cfg.vm.provision :shell, :path => "install_kafka_manager.sh", :args => kraft
          if kraft !="yes"
	          cfg.vm.provision :shell, :path => "install_cmak_cluster.sh"
					end
			  end
			end

    end # end config
  end # end nodes

end 


