# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # postgres server
  config.vm.define "postgres" do |postgres|
    postgres.vm.box = "ubuntu/bionic64"
    postgres.vm.hostname = "postgres"
    postgres.vm.box_url = "ubuntu/bionic64"
    postgres.vm.network :private_network, ip: "192.168.63.2"
    postgres.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "postgres"]
      v.customize ["modifyvm", :id, "--cpus", "1"]
    end
    config.vm.provision "shell", inline: <<-SHELL
      sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config    
      service ssh restart
    SHELL
    postgres.vm.provision "shell", path: "install_postgres.sh"
  end
end


