Vagrant.configure(2) do |config|

	# before you must install these plugins to speed up vagrant provisionning
  # vagrant plugin install vagrant-faster
  # vagrant plugin install vagrant-cachier

  config.cache.auto_detect = true
	# Set some variables
  etcHosts = ""

	# some settings for common server (not for haproxy)
  common = <<-SHELL
  apt update -qq 2>&1 >/dev/null
  apt install -y -qq curl software-properties-common git vim tree net-tools telnet git python3-pip sshpass nfs-common 2>&1 >/dev/null
  sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
  usermod -p '$y$j9T$Umn3rEIpmy0I9.wcU/Qc/.$X.e6wlDFVw.uN7kt636eNKixnt9GiGu4ypcy2JPmst2' vagrant
  sed -i s/"#PermitRootLogin .*"/"PermitRootLogin yes"/g /etc/ssh/sshd_config
  systemctl restart sshd
  SHELL

  #config.vm.box = "debian/bullseye64"
  #config.vm.box_url = "debian/bullseye"
  config.vm.box = "bento/debian-11"
  config.vm.box_url = "bento/debian-11"


	# set servers list and their parameters
	NODES = [
  	{ :hostname => "chef-server", :ip => "192.168.14.51", :cpus => 2, :mem => 4096, :type => "chef-server" },
  	{ :hostname => "chef-client", :ip => "192.168.14.49", :cpus => 2, :mem => 4096, :type => "chef-client" },
  	{ :hostname => "chef-workstation", :ip => "192.168.14.48", :cpus => 2, :mem => 4096, :type => "chef-workstation" },
  	{ :hostname => "chef-node", :ip => "192.168.14.52", :cpus => 2, :mem => 4096, :type => "chef-client" }
	]

	# define /etc/hosts for all servers
  NODES.each do |node|
			etcHosts += "echo '" + node[:ip] + "   " + node[:hostname] + "'>> /etc/hosts" + "\n"
  end #end NODES

	# run installation
  NODES.each do |node|
    config.vm.define node[:hostname] do |cfg|
			cfg.vm.hostname = node[:hostname]
      cfg.vm.network "private_network", ip: node[:ip]
      cfg.vm.provider "virtualbox" do |v|
				v.customize [ "modifyvm", :id, "--cpus", node[:cpus] ]
        v.customize [ "modifyvm", :id, "--memory", node[:mem] ]
        v.customize [ "modifyvm", :id, "--natdnshostresolver1", "on" ]
        v.customize [ "modifyvm", :id, "--natdnsproxy1", "on" ]
        v.customize [ "modifyvm", :id, "--name", node[:hostname] ]
				v.customize [ "modifyvm", :id, "--ioapic", "on" ]
        v.customize [ "modifyvm", :id, "--nictype1", "virtio" ]
      end #end provider
			
			#for all
      cfg.vm.provision :shell, :inline => etcHosts
			cfg.vm.provision :shell, :inline => common
			cfg.vm.provision :shell, :path => "install_xavki.sh"
      if node[:type] == "chef-server"
        cfg.vm.provision :shell, :path => "install_chef_server.sh"
      end
      if node[:type] == "chef-workstation"
        cfg.vm.provision :shell, :path => "install_chef_workstation.sh"
      end
    end # end config
  end # end nodes

end 


