# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "kubmaster" do |kub|
    kub.vm.box = "ubuntu/bionic64"
    kub.vm.hostname = 'kubmaster'
    #kub.vm.provision "docker"
    kub.vm.box_url = "ubuntu/bionic64"
    kub.vm.network :private_network, ip: "192.168.56.101"

    kub.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--name", "kubmaster"]
      v.customize ["modifyvm", :id, "--cpus", "2"]
    end
	
	#config.vm.provision "shell", inline: <<-SHELL
      #sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
      #service ssh restart
    #SHELL
    #kub.vm.provision "shell", path: "install_docker.sh"
	
  end

  config.vm.define "kubnode1" do |kubnode|
    kubnode.vm.box = "ubuntu/bionic64"
    kubnode.vm.hostname = 'kubnode1'
    #kubnode.vm.provision "docker"
    kubnode.vm.box_url = "ubuntu/bionic64"

    kubnode.vm.network :private_network, ip: "192.168.56.102"

    kubnode.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--name", "kubnode1"]
      v.customize ["modifyvm", :id, "--cpus", "2"]
    end
	
	#config.vm.provision "shell", inline: <<-SHELL
     # sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
     # service ssh restart
   # SHELL
   # kubnode.vm.provision "shell", path: "install_docker.sh"
	
  end
end

