Vagrant.configure(2) do |config|
  common = <<-SHELL
  sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
  sudo systemctl restart sshd
  SHELL
	config.vm.box = "centos/8"
	config.vm.box_url = "centos/8"

	config.vm.define "debelkrh" do |control|
		control.vm.hostname = "debelkrh"
		control.vm.network "private_network", ip: "192.168.20.110"
		control.vm.provider "virtualbox" do |v|
			v.customize [ "modifyvm", :id, "--cpus", "4" ]
			v.customize [ "modifyvm", :id, "--memory", "4096" ]
			v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      			v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
			v.customize ["modifyvm", :id, "--name", "debelkrh"]
		end
		control.vm.provision :shell, :inline => common
    control.vm.provision "shell", path: "install_elk.sh"
	end

	config.vm.define "srv11rh" do |srv11|
		srv11.vm.hostname = "srv11rh"
	  srv11.vm.box = "ubuntu/bionic64"
	  srv11.vm.box_url = "ubuntu/bionic64"
		srv11.vm.network "private_network", ip: "192.168.20.111"
		srv11.vm.provider "virtualbox" do |v|
			v.customize [ "modifyvm", :id, "--cpus", "1" ]
			v.customize [ "modifyvm", :id, "--memory", "512" ]
			v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      			v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
			v.customize ["modifyvm", :id, "--name", "srv11rh"]
		end
		srv11.vm.provision :shell, :inline => common
	end

end

