Vagrant.configure(2) do |config|

	# before you must install these plugins to speed up vagrant provisionning
  # vagrant plugin install vagrant-faster
  # vagrant plugin install vagrant-cachier

  config.cache.auto_detect = true
	# Set some variables
  etcHosts = ""
  rabbitmq = ""
  prometheus = ""

  # Check ingress controller
  case ARGV[0]
    when "provision", "up"

    print "Do you want to install rabbitmq (yes/no) ?\n"
    rabbitmq = STDIN.gets.chomp
    print "\n"

    print "Do you want to install consul (yes/no) ?\n"
    consul = STDIN.gets.chomp
    print "\n"

    if consul == "yes"
      print "Do you want to install consul services (yes/no) ?\n"
      consul_services = STDIN.gets.chomp
      print "\n"
    end

    print "Do you want to install prometheus (yes/no) ?\n"
    prometheus = STDIN.gets.chomp
    print "\n"

  end

	# some settings for common server (not for haproxy)
  common = <<-SHELL
  sudo apt update -qq 2>&1 >/dev/null
  sudo apt install -y -qq curl software-properties-common git vim tree net-tools telnet git python3-pip sshpass nfs-common 2>&1 >/dev/null
  curl -Lsf https://sh.benthos.dev | bash 2>&1 >/dev/null
  sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
  sudo systemctl restart sshd
  SHELL

  config.vm.box = "debian/bullseye64"
  config.vm.box_url = "debian/bullseye"


	# set servers list and their parameters
	NODES = [
  	{ :hostname => "oth4", :ip => "192.168.12.51", :cpus => 4, :mem => 4096, :type => "external" },
  	{ :hostname => "rmq1", :ip => "192.168.12.48", :cpus => 2, :mem => 1024, :type => "rmq_leader" },
  	{ :hostname => "rmq2", :ip => "192.168.12.49", :cpus => 2, :mem => 1024, :type => "rmq_follower" },
  	{ :hostname => "rmq3", :ip => "192.168.12.50", :cpus => 2, :mem => 1024, :type => "rmq_follower" }
	]

	# define /etc/hosts for all servers
  NODES.each do |node|
			etcHosts += "echo '" + node[:ip] + "   " + node[:hostname] + "'>> /etc/hosts" + "\n"
    if node[:type] == "gitlab"
      etcHosts += "echo '" + node[:ip] + "   " + gitlabUrl + " registry." + gitlabUrl + "' >> /etc/hosts" + "\n"
    end
  end #end NODES

	# run installation
  NODES.each do |node|
    config.vm.define node[:hostname] do |cfg|
			cfg.vm.hostname = node[:hostname]
      cfg.vm.network "private_network", ip: node[:ip]
      cfg.vm.provider "virtualbox" do |v|
				v.customize [ "modifyvm", :id, "--cpus", node[:cpus] ]
        v.customize [ "modifyvm", :id, "--memory", node[:mem] ]
        v.customize [ "modifyvm", :id, "--natdnshostresolver1", "on" ]
        v.customize [ "modifyvm", :id, "--natdnsproxy1", "on" ]
        v.customize [ "modifyvm", :id, "--name", node[:hostname] ]
				v.customize [ "modifyvm", :id, "--ioapic", "on" ]
        v.customize [ "modifyvm", :id, "--nictype1", "virtio" ]
      end #end provider
			
			#for all
      cfg.vm.provision :shell, :inline => etcHosts
			cfg.vm.provision :shell, :inline => common
      cfg.vm.provision :shell, :path => "install_node_exporter.sh"

      if rabbitmq == "yes"
        if node[:type] == "rmq_leader"
          cfg.vm.provision :shell, :path => "install_rabbitmq.sh", :args => "leader"
			  end

        if node[:type] == "rmq_follower"
          cfg.vm.provision :shell, :path => "install_rabbitmq.sh", :args => "follower"
			  end
			end

      if consul == "yes"
        if node[:type] == "external"
          cfg.vm.provision :shell, :path => "install_consul.sh", :args => "consul_master"
			  end
        if node[:type] != "external"
          cfg.vm.provision :shell, :path => "install_consul.sh", :args => ["consul_agent",consul_services]
        end
			end

      if prometheus == "yes"
        if node[:type] == "external"
          cfg.vm.provision :shell, :path => "install_prometheus.sh"
			  end
      end

    end # end config
  end # end nodes

end 


