Vagrant.configure(2) do |config|
  common = <<-SHELL
  sudo yum -y install vim tree net-tools telnet git python3
  sudo echo "autocmd filetype yaml setlocal ai ts=2 sw=2 et" > /home/vagrant/.vimrc
  sudo echo "alias python=/usr/bin/python3" >> /home/vagrant/.bashrc
  sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
  sudo systemctl restart sshd
  SHELL
	config.vm.box = "centos/7"
	config.vm.box_url = "centos/7"

	config.vm.define "k3s" do |control|
		control.vm.hostname = "k3s"
		control.vm.network "private_network", ip: "192.168.20.110"
		control.vm.provider "virtualbox" do |v|
			v.customize [ "modifyvm", :id, "--cpus", "2" ]
			v.customize [ "modifyvm", :id, "--memory", "2048" ]
			v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      			v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
			v.customize ["modifyvm", :id, "--name", "k3s"]
		end
		config.vm.provision :shell, :inline => common
	end

	config.vm.define "k3sw" do |control|
		control.vm.hostname = "k3sw"
		control.vm.network "private_network", ip: "192.168.20.111"
		control.vm.provider "virtualbox" do |v|
			v.customize [ "modifyvm", :id, "--cpus", "2" ]
			v.customize [ "modifyvm", :id, "--memory", "1024" ]
			v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      			v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
			v.customize ["modifyvm", :id, "--name", "k3sw"]
		end
		config.vm.provision :shell, :inline => common
	end

  # Serveur gitlab
  config.vm.define "glab" do |gitlab|
    gitlab.vm.box = "debian/buster64"
    gitlab.vm.hostname = "glab"
    gitlab.vm.box_url = "debian/buster64"
    gitlab.vm.network :private_network, ip: "192.168.20.99"
    gitlab.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      v.customize ["modifyvm", :id, "--memory", 4096]
      v.customize ["modifyvm", :id, "--name", "glab"]
      v.customize ["modifyvm", :id, "--cpus", "2"]
    end
    config.vm.provision "shell", inline: <<-SHELL
      sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
      service ssh restart
    SHELL
    gitlab.vm.provision "shell", path: "install_gitlab.sh"
  end

end

