# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # lxd server
  config.vm.define "lxd" do |lxd|
    lxd.vm.box = "ubuntu/bionic64"
    lxd.vm.hostname = "lxd"
    lxd.vm.box_url = "ubuntu/bionic64"
    lxd.vm.network :private_network, ip: "192.168.58.2"
    lxd.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "lxd"]
      v.customize ["modifyvm", :id, "--cpus", "1"]
    end
    config.vm.provision "shell", inline: <<-SHELL
      sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config    
      service ssh restart
    SHELL
  end
end


